
import React, { useState } from 'react';
import { generateImage } from '../services/geminiService';
import { AspectRatio } from '../types';

const ImageGenerator: React.FC = () => {
  const [prompt, setPrompt] = useState('A beautiful watercolor painting of a sudoku puzzle board in a zen garden');
  const [aspectRatio, setAspectRatio] = useState<AspectRatio>('1:1');
  const [isLoading, setIsLoading] = useState(false);
  const [generatedImage, setGeneratedImage] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!prompt) return;
    setIsLoading(true);
    setError(null);
    setGeneratedImage(null);
    try {
      const imageUrl = await generateImage(prompt, aspectRatio);
      if (imageUrl) {
        setGeneratedImage(imageUrl);
      } else {
        setError('Failed to generate image. Please try again.');
      }
    } catch (err) {
      setError('An error occurred while generating the image.');
      console.error(err);
    } finally {
      setIsLoading(false);
    }
  };

  const aspectRatios: AspectRatio[] = ['1:1', '16:9', '9:16', '4:3', '3:4'];

  return (
    <div className="w-full max-w-3xl mx-auto p-4 bg-slate-800/50 rounded-lg shadow-xl mt-8">
      <h2 className="text-2xl font-bold text-center mb-4 text-cyan-400">AI Image Generator</h2>
      <form onSubmit={handleSubmit} className="space-y-4">
        <div>
          <label htmlFor="prompt" className="block text-sm font-medium text-slate-300 mb-1">
            Prompt
          </label>
          <textarea
            id="prompt"
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
            className="w-full p-2 bg-slate-700 border border-slate-600 rounded-md focus:ring-cyan-500 focus:border-cyan-500 text-slate-100"
            rows={3}
            placeholder="e.g., A robot solving a sudoku puzzle"
          />
        </div>
        <div>
          <label htmlFor="aspectRatio" className="block text-sm font-medium text-slate-300 mb-1">
            Aspect Ratio
          </label>
          <select
            id="aspectRatio"
            value={aspectRatio}
            onChange={(e) => setAspectRatio(e.target.value as AspectRatio)}
            className="w-full p-2 bg-slate-700 border border-slate-600 rounded-md focus:ring-cyan-500 focus:border-cyan-500"
          >
            {aspectRatios.map(ar => <option key={ar} value={ar}>{ar}</option>)}
          </select>
        </div>
        <button
          type="submit"
          disabled={isLoading}
          className="w-full px-4 py-2 bg-indigo-600 text-white font-semibold rounded-md hover:bg-indigo-500 disabled:bg-slate-600 disabled:cursor-not-allowed transition-colors"
        >
          {isLoading ? 'Generating...' : 'Generate Image'}
        </button>
      </form>
      {error && <p className="text-red-500 mt-4 text-center">{error}</p>}
      {isLoading && (
        <div className="mt-6 text-center">
            <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-cyan-400 mx-auto"></div>
            <p className="mt-2 text-slate-400">Creating your masterpiece...</p>
        </div>
      )}
      {generatedImage && (
        <div className="mt-6 p-2 bg-slate-900 rounded-lg">
          <img src={generatedImage} alt="Generated by AI" className="w-full h-auto rounded-md" />
        </div>
      )}
    </div>
  );
};

export default ImageGenerator;
